#
# This file was last modified at 2023.11.20 00:10 by Victor N. Skurikhin.
# This is free and unencumbered software released into the public domain.
# For more information, please refer to <http://unlicense.org>
# application.properties
# $Id$
#
greeting:
  message: "hello"

mp:
  jwt:
    verify:
      publickey:
        issuer: "https://svn.su/issuer"
        location: publicKey.pem

quarkus:
  cache:
    caffeine:
      "login_request":
        expire-after-write: 90S
        metrics-enabled: true
      "session_get":
        expire-after-write: 90S
        metrics-enabled: true
      "json_record_get":
        expire-after-write: 90S
        metrics-enabled: true
      "user_get":
        expire-after-write: 90S
        metrics-enabled: true
      "user_page":
        expire-after-write: 90S
        metrics-enabled: true
  datasource:
    db-kind: postgresql
    db-version: 14.0
    jdbc: false
    password: ${DAY_BOOK_DATASOURCE_PASSWORD:password}
    username: ${DATASOURCE_USERNAME:dbuser}
    reactive:
      idle-timeout: PT1M
      max-size: 20
      reconnect-interval: PT1S
      url: ${DAY_BOOK_DATASOURCE_REACTIVE_URL:postgresql://localhost:5432/db}
  grpc:
    server:
      port: 9901
  hibernate-orm:
    database:
      generation: none
    dialect: PostgreSQL
    log:
      sql: true
      format-sql: true
      bind-parameters: true
  http:
    enable-compression: true
    compress-media-types: text/html,text/plain,text/xml,text/css,text/javascript,application/javascript,application/json
    non-application-root-path: /q
    root-path: /
    port: 8801
    proxy:
      enable-forwarded-host: true
      enable-forwarded-prefix: true
      proxy-address-forwarding: true
    cors:
      allowed-origins: https://svn.su
  jackson:
    serialization-inclusion: non_null
  log:
    category:
      "su.svn.daybook3":
        level: TRACE
    console:
      format: "%d{HH:mm:ss} %-5p request.id=%X{request.id} [%c{2.}] (%t) %s%n"
    level: ${DAY_BOOK_LOG_LEVEL:INFO}
    min-level: ${DAY_BOOK_LOG_MIN_LEVEL:TRACE}
  micrometer:
    export:
      prometheus:
        path: metrics
  native:
    resources:
      includes: publicKey.pem
  resteasy:
    gzip:
      enabled: true
      max-input: 10M
  smallrye:
    jwt:
      new-token:
        issuer: "https://svn.su/issuer"
        lifespan: ${DAY_BOOK_SMALLRYE_JWT_NEW_TOKEN_LIFESPAN:36000}
  smallrye-openapi:
    always-run-filter: true
    security-scheme-name: "day-book"
  swagger-ui:
    always-include: true
    path: /q/auth/openapi
  vertx:
    prefer-native-transport: true

smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem

su:
  svn:
    password:
      iteration: 33
      keylength: 256
    secret: ${DAY_BOOK_SECRET:b19bba7cd53a417494756ae9d7b9bbeed94d93d9d44c403c97b1d071b6974d80adc2221c03dd496f924317e}
