@startuml

!include C4.puml
!include C4_Context.puml
!include C4_Container.puml
!include C4_Component.puml

LAYOUT_WITH_LEGEND()

title DayBook System Context Diagram

top to bottom direction

Person(admin, "Admin", "A admin of the DayBook")
Person_Ext(user, "User", "A user of the DayBook")

Enterprise_Boundary(c0, "DayBook FrontEnd") {
    System(DayBookUISystem, "DayBook UI", "DayBook FrontEnd")
    System(DayBookAPISystem, "DayBook API", "DayBook FrontEnd")
}

Enterprise_Boundary(c1, "DayBook BackEnd") {
    System(DayBookBackendSystem, "DayBook Backend", "DayBook BackEnd")
    SystemDb(DayBookDbSystem, "DB", "DayBook BackEnd")
    SystemQueue(DayBookKafkaSystem, "Kafka", "DayBook BackEnd")
}

Rel_R(admin, DayBookUISystem, "Admin the system  ")
Rel_L(user, DayBookUISystem, " Uses the system")
Rel(DayBookUISystem, DayBookAPISystem, "Uses RESTful")
Rel(DayBookAPISystem, DayBookBackendSystem, "Uses gRPC")
Rel(DayBookBackendSystem, DayBookDbSystem, "Uses DB")
Rel(DayBookBackendSystem, DayBookKafkaSystem, "Messaging")

@enduml