pipeline {
    agent any
    stages {
        stage('git branch main') {
            steps {
                git branch: 'main', url: 'https://github.com/vskurikhin/DayBook-3.0.git'
            }
        }
        stage('gradle update') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: "PGS00X_CLUSTER",
                    usernameVariable: 'USERNAME',
                    passwordVariable: 'PASSWORD'
                )]) {
                    sh '''
                      set -x
                      DBUSER=${USERNAME} \
                      DBPASS=${PASSWORD} \
                      DBURL=${DBURL} \
                      gradle update
                    '''
                }
            }
        }
    }
}